import { combineReducers } from 'redux';
import auth from '../redux/auth';
import photo from '../redux/photo';
import photos from '../redux/photos';
import upload from '../redux/upload';
import loading from '../redux/loading';
import tags from '../redux/tags';
import user from '../redux/user';
import googlePicker from '../redux/googlePicker';
import searching from "../redux/searching";
import album from "../redux/album";
import searchTags from "../redux/searchTags";
import keyboard from "../redux/keyboard";
const rootReducer = combineReducers({auth, photo, photos, loading, googlePicker, upload, tags, user, searching, album, searchTags, keyboard});
export default rootReducer;
